### ISSUE TITLE
LTM/GPS over Frsky Telemetry User Data

### ISSUE THREAD

**Issue by SamuelBrucksch** [raul-ortega/amv-open360tracker-32bits#2]
Hi Raul,

i was wondering, if it makes more sense to put out LTM on the flightcontrol and send that over Frsky telemetry instead of using native Frsky telemetry.

You can input user data on Frsky Protocol with 9600baud and a maximum of 1200bit/s if you dont use native frsky telemetry. 

LTM has already the checkbyte and much more accurate data included (also fixtype and so on), Frsky telemetry is a pain in the ass if you want to check for correctness of data - remember the hassle we had with the DJT module and wrong incoming coordinates?

So what would be needed is a telemetry that defines the way of incoming data (in this case frsky serial bridge) and the telemetry of the data (in this case LTM). So it would actually require two telemetry systems to be set.

The same works with GPS. You can set NMEA GPS to 9600baud and 3hz if you disable all unneccesary NMEA sentences. In that case we have the frsky serial bridge again but as a decoder we need the GPS parser.

What do you think?

Cheers

Samuel

**Comment by raul-ortega** [comment]
In this moment this firmware is able to decode input LTM format telemetry data(I added the protocol to the 8bit version, and it is already ported to the 32bit version).  I'm not sure if I've understood your goal. Do you mean that you want to decode LTM frames which are sent from the aircraft/drone to the antenna tracker as encapsulated packets within the FRSKY telemetry packets?

**Comment by SamuelBrucksch** [comment]
You can decode User Data on the RX side (Data ID 0xFD):
www.frsky-rc.com/download/down.php?id=128

Actually it is the same data stream and everything is the same as when using native frsky Protocol. The only difference is, that you now do not parse the hub data (0x5E) but the data that is in this 0xFD package is the LTM or GPS data.

Already tried that with GPS a few years ago and it works well if you do not send too much data. But as LTM fits a 2400baud stream there shouldnt be any problems.

In the method processFrskyPacket(uint8_t\* packet){} the only thing you have to change is the parseTelemHubByte(packet). That needs to be exchanged with the LTM/GPS parse method.

Not sure if this works with X-series telemetry though... have to investigate on that. But it somehow should work.

**Comment by raul-ortega** [comment]
It sounds good!

Latest versions of cleanflight implement LTM telemetry protocol, so I'd need to do before a bit of work in the side of cleanflight to encapsulate LTM frames into FRSKY user frames, so I'd test it with real telemetry data from my ZMR250.

I'll try it after I finish with the configuration menu for the OLED display.

**Comment by marksev1** [comment]
Samuel are you talking about using ltm as a bidirectional protocol to give the FC commands. Or just transmitting the ltm through a frsky receiver? Also will the antenna tracker function the same as it did before with just the normal ltm will it be able to receive both types?

**Comment by SamuelBrucksch** [comment]
No, the Frsky protocol is bad in error detection. LTM has at least some kind of error detection, even if it is not that strong its still better than nothing. Also LTM has a fix type which is missing in frsky protocol which is important for setting auto home in the tracker.

The frsky protocol was developed in a way, that you can send custom data. The frsky hub creates such custom data with the id 0x5E which is the frsky hub package that includes all the telemetry data the FCs send out.

But you can as well send other stuff over it. I already sent NMEA over the custom data. 

So what i want is LTM over this custom data so i can make use of LTM without using a 433mhz system or so. LTM has much more important data included that Frsky is missing. Also the update rate is much higher.

**Comment by raul-ortega** [comment]
Yes, I understood you, I meant that for doing it I need before to prepare cleanflight to be able to encapsulate LTM over FRSKY D user data packets, so I'll be able to send the packets from my ZMR250 to the antennar tracker.

This week I'll start with this issue...

**Comment by raul-ortega** [comment]
Dear Samuel, I have a question for you? Which aground control app could I use to test LTM frames???

**Comment by SamuelBrucksch** [comment]
Raul, that reply was for mark, as he did not understand me ;)

Not sure if there is a GCS that directly supports LTM on PC or so. But i think you need to write your own if you want to debug anyways as you first have to decode the frsky frames and only then you can access the LTM frames. there might be a Frsky Parser and a LTM parser but none that combines both.

**Comment by marksev1** [comment]
There is. Mwptools for Ubuntu on computer and Ezgui on android also supports it. (LTM protocol I mean)

**Comment by raul-ortega** [comment]
marksev1, are you sure that EZ-GUI support LTM?

**Comment by raul-ortega** [comment]
Oh, yes, it works... 
I added basic outgoin telemetry data in LTM format from the antena tracker, and now I can see position and altitude in EZ-GUI, je je ...

**Comment by raul-ortega** [comment]
I started working in this issue yesterday. My first step has been to modify cleanflight code to be sure it only sends G type frames of LTM protocol.
The first test I've done is sending one frame each 250 ms to the FrSky Rx with 9600 bauds (softserial).
I captured the frames into a file and filtered the 7E FD frames manually, removing FRSKY D headers, tails and unused bytes and decoded the stream using the LTM parser (not modified yet).

The result is that after 37 $TG headers detected, the CRC values match only for one of the frames. Too many corrupts frames at 250 ms.

I'll increase the frecuency to 300ms, and if the result is similar I'll forget this issue (less than 4 packets per seconds gives a bad tracker behaivor).

**Comment by SamuelBrucksch** [comment]
Frsky D-Series custom data allows 120byte/s. The G-Frame is 18byte. So there should not be any problems with 4hz.
-   G Frame (GPS position) (2hz @ 1200 bauds , 5hz >= 2400 bauds): 18BYTES
-    0x24 0x54 0x47 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF  0xFF   0xC0  
-     $     T    G  --------LAT-------- -------LON---------  SPD --------ALT-------- SAT/FIX  CRC

On 2hz@1200baud it should be 36byte/s if only using G-frames and on 5hz it should be 90byte/s. Please check if any other data is transmitted as well.

If setting LTM to 1200baud refresh rate the overall data rate should be 108byte/s without OSD frame when all sentences are enabled.

**Comment by raul-ortega** [comment]
Please, correct me if I'm wrong in my calculations:

Máximum byte rate at 1200 bauds = 1200 / 10bits = 120 bytes/second 

Time required to send a G frame at 1200 bauds = 18 bytes \* 1000 ms  / 120 bytes = 150 milliseconds.

Is this ok? If yes, with it in mind, I could transmit G frames at 250 ms (4 hz) without problem. But my preliminary results says that the frames content errors.

But I've observed in the captured data many frames which start with header **7E EF**, and they are inserted between the 7E FD frames. I removed manually all this frames thinking that they are part of the FrSky D communication protocol (I haven't found information about what those frames transport). Do you have any information about this?

**Comment by SamuelBrucksch** [comment]
No, Frsky D-series runs on 9600baud, but maximum transfer rate is 1200bit/s (sorry, 120byte/s was wrong, its actually 150byte/s), if you transfer more, the data will be corrupted.

You can not just remove frames manually to see if the data in those frames is correct. You need to parse the LTM frames out of Frsky telemetry:
http://www.frsky-rc.com/download/down.php?id=128

See chapter 3.1.4

Head | PRIM | Length | 0x00 | user data | End
0x7E | 0xFD | 0x?? | 0x00 | byte1..byte6 | 0x7E

LTM in this case would be byte1...byte6

In the already existing code byte1...byte6 is the data, that is given to parseTelemHubByte(packet). the telemetry hub data is actually custom data as well. So it is transmitted in the same frame. You can not transmit user data and hub data at the same time. As that will corrupt the packages as well, as user data and hub data would be mixed together.

**Comment by raul-ortega** [comment]
I think that you haven't understood what I mean, or I haven't explained well ...

What I men is that I only send 18 bytes every 250 ms, that is less than 120 bytes/second, so It should work.

In the other hand, I remove manualy every thing in my file to get only the 18 LTM bytes (the are splited into several 7E FD, soy I can analize in my PC with the LTM parser as pure LTM frames.

**Comment by SamuelBrucksch** [comment]
You can not just remove 7E and FD, you have to use the frsky parser to get the user data out.

**Comment by sppnk** [comment]
Hello gurús, :-) I am making some preliminar tests for the antenna tracker with a downllink LTM telemetry with openlrsng modules.

I am trying to decode LTM from cleanflight with EZGUI, but I have no good results. I have set USART1 sharing MSP (bluetooth for configuration of CF) and the rx pin of my openlrsng receiver.

In my transmitter I can see rssi and tssi data (is a 9x modified), and I send the downstream data to my tablet through a bluetooth adapter from my orangerx TX. When I arm the model I start to see the data stream in a bluetooth terminal in my tablet. I see clearly '$TGxxx', $TAxxx' and so on, so I think the LTM is there, and in good shape.

But in EZGUI the good packets come from time to time, every 10 seconds or so. 

Do you think I should configure openlrsng just to 'passtrough' in order to get the LTM in my tablet? Are there any other apk to test LTM (I guess Taulabs do, but minimun bps is 38400). Thks.

**Comment by SamuelBrucksch** [comment]
This question is totally wrong here i would say...

**Comment by raul-ortega** [comment]
I haven't forgot this topic, but I´ve decided not to implement it yet because I have been working in an improvement that could solve the problem caused by corrupted data in coordinates. It consists in a system which discards the current position if it causes that the speed of the dron exceeds a set limit.

**Comment by raul-ortega** [comment]
I added the speed filter to source code at https://github.com/raul-ortega/u360gts repository.
Please could you move this issue to there.This repository will be removed soon. Thanks.
