### ISSUE TITLE
Automatic pan servo mid calibration

### ISSUE THREAD

**Issue by SamuelBrucksch** [raul-ortega/amv-open360tracker-32bits#5]
There is an easy way for an automatic pan servo mid calibration. You start turning the tracker with full power (1000us) (or any other value +-200 around 1500 for faster calibration). Then every few seconds you go down by 5 or 10 or whatever steps. The tracker will get slower and slower and eventually stop at some point. Still you continue increasing the steps until the tracker starts to rotate again. Once the tracker stops you save the lower value and once it starts to rotate again you will save the higher value. Then take the midpoint of that value.

For example 1475 the tracker stops and 1510 it starts again, then the midpoint is 1492. You can see if the tracker stops and starts again by checking if the heading changes.

As this calibration normally needs to be done only one time it can take a bit longer. The smaller the increased steps, the more accurate is the mid position (but the longer the calibration).

**Comment by raul-ortega** [comment]
This issue has been solved at https://github.com/raul-ortega/u360gts repository (only source code, hex version 7.0 not yet uploaded).
Please could you move this issue to there? This repository will be removed soon. Thanks.
