### ISSUE TITLE
MFD does not work

### ISSUE THREAD

**Issue by SamuelBrucksch** [raul-ortega/amv-open360tracker-32bits#6]
MFD protocol itself works, but it looks like theres something wrong when trying to use the testmode where the tracker should rotate from 0 - 90 - 180 - 270°. Tilt works as expected (0° - 45° - 90° - 0°) but pan only rotates continiously without stopping. On the display i can see that heading changes, azimuth changes to the mentioned values but the value in the bracket behind A always stays 0. Distance for these tests for example are 1000 and 1 and height 1 and 1000. They are coming from the driver.

As the testmode already rotates endlessly i guess it will do with real telemetry data as well?

**Comment by raul-ortega** [comment]
Please could you move this issue to https://github.com/raul-ortega/u360gts repository ?
This repository will be removed soon. Thanks.
