### ISSUE TITLE
Smartport-Telemetry not read correctly

### ISSUE THREAD

**Issue by MarenB** [raul-ortega/amv-open360tracker-32bits#7]
Hi!

I am using the built-in Bluetooth of my Taranis-E to transfer the telemetry from a DIY-GPS (from Samuel/Rangarid) via an HM-10 BT BLE Module to the tracker. 
While this works fine for the 8-bit variant, the 32-bit solution only reads the altitude. I don't get any LAT/LON or Sats on the LCD of the tracker while it's fine on the Taranis itself.
I can provide a record of what's coming out of the receiving BT-module, if that helps.

**Comment by raul-ortega** [comment]
Please could you move this issue to https://github.com/raul-ortega/u360gts repository ?
This repository will be removed soon. Thanks.
